name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ os }}
#    fail-fast: false
    matrix:
      os: [ubuntu-latest, windows-latest]
      build_type: [Release]

      steps:
        - uses: threeal/cmake-action@main
          with:
            run-build: false
            generator: Ninja
            c-compiler: clang
            cxx-compiler: clang++
        - uses: actions/checkout@v4
        - uses: actions-rs/cargo@v1
          with:
            command: test
        # Build commands    
        - run: cargo run -- init
        - run: cargo run -- build-entry -G vs 10.0.0

  # windows:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       command: test
  #   - run: cargo run -- init
  #   - run: cargo run -- build-entry -G vs 10.0.0

  # macos:
  #   runs-on: macos-10.15
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       command: test
  #   - run: cargo run -- init
  #   - run: cargo run -- build-entry 10.0.0

  # linux:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #     - run: cargo run -- init
  #     - run: cargo run -- build-entry 10.0.0
      

  check-format:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  check-clippy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
