name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

      steps:
        - uses: actions/checkout@v4
        - uses: actions-rs/cargo@v1
          with:
            command: test
        - name: Set reusable strings
          id: strings
          shell: bash
          run: |
            echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        # Build commands    
        - run: cargo run -- init
        - run: cargo run -- build-entry -G vs 10.0.0

  # windows:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       command: test
  #   - run: cargo run -- init
  #   - run: cargo run -- build-entry -G vs 10.0.0

  # macos:
  #   runs-on: macos-10.15
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       command: test
  #   - run: cargo run -- init
  #   - run: cargo run -- build-entry 10.0.0

  # linux:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #     - run: cargo run -- init
  #     - run: cargo run -- build-entry 10.0.0
      

  check-format:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  check-clippy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
