name: Rust

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
#    fail-fast: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    # steps
    steps:
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        # generator: Ninja
        # c-compiler: clang
        # cxx-compiler: clang++
        run-build: false
    - uses: actions/checkout@v4
    - uses: actions-rs/cargo@v1
      with:
        command: test
    # Build commands    
    - run: cargo run -- init
    - run: cargo run -- build-entry -G vs 10.0.0

  # windows:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       command: test
  #   - run: cargo run -- init
  #   - run: cargo run -- build-entry -G vs 10.0.0

  # macos:
  #   runs-on: macos-10.15
  #   steps:
      # - uses: actions/checkout@v1
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      # - run: cargo run -- init
      # - run: cargo run -- build-entry 10.0.0

  # linux:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #     - run: cargo run -- init
  #     - run: cargo run -- build-entry 10.0.0
      

  check-format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  check-clippy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
