name: Rust

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    # steps
    steps:
      - uses: actions/checkout@v4
      - name: get-cmake
        uses: lukka/get-cmake@v3.29.2
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
            cache: 'pip'
      - run: pip install setuptools
      # Build commands
      - name: Build
        # timeout-minutes: 80000
        continue-on-error: true
        run: |
          cargo run -- init
          cargo run -- build-entry -G Ninja 18.0.1

  # windows:
  #   runs-on: windows-2019
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       command: test
  #   - run: cargo run -- init
  #   - run: cargo run -- build-entry -G vs 10.0.0

  # macos:
  #   runs-on: macos-10.15
  #   steps:
      # - uses: actions/checkout@v1
      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      # - run: cargo run -- init
      # - run: cargo run -- build-entry 10.0.0

  # linux:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #     - run: cargo run -- init
  #     - run: cargo run -- build-entry 10.0.0
      

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  check-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
